spring:
  application:
    name: redis_blog_app
  
  datasource:
    url: jdbc:postgresql://localhost:5454/postgres?currentSchema=postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: blog_app
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  servlet:
    context-path: /api